openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Respiratory Depression Risk Indicator'
  description: 'This object scans a list of prescriptions and determines if the patient is at risk greater for drug-induced respiratory depression because of being exposed simultaneously to a known dangerous combination of an opioid, a benzodiazepine, and a muscle relaxant.'
servers:
  - url: 'https://kgrid-activator.herokuapp.com/99999/10103/v0.0.1'
paths:
  /tripleThreatDetector:
    post:
      description: tripleThreatDetector.
      operationId: tripleThreatDetector
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/druglist'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    druglist:
      required:
        - rxcuis
      properties:
        rxcuis:
          type: string
          example: '106500,200240,856917,994226,197446,801958'
    output:
      required:
        - result
      properties:
        result:
          type: string
          example: '{respiratoryDepression:false,summary:{opioid:false,bzd:false,mr:false},detail:{}}'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
